User defined function
DataEngineersNZ/dbt-snowflake-datops-materilizations pull request #1
Opened 2022-08-05 02:07 UTC by adhakal321

Hi Jon,
Please review my PR.

2022-08-07 20:52 UTC, jonhopper-dataengineers requested changes
you need to add some docs into the yml file aswell for the macros.

2022-08-07 20:52 UTC, jonhopper-dataengineers commented on macros/user_defined_functions/snowflake__user_defined_function.sql
> +  The idea behind this materialization is for ability to define CREATE STORED PROCEDURE statements and have dbt use the necessary logic
change this to be UDF instead

2022-08-07 22:08 UTC, adhakal321 commented on macros/user_defined_functions/snowflake__user_defined_function.sql
> +  The idea behind this materialization is for ability to define CREATE STORED PROCEDURE statements and have dbt use the necessary logic
changed to UDF

2022-08-09 22:30 UTC, jonhopper-dataengineers approved these changes

2022-08-09 22:31 UTC, merged